#ifndef UIAP_HAPTIC_PATTERN_PROTOCOL_H
#define UIAP_HAPTIC_PATTERN_PROTOCOL_H

/* Feature Report: [ID, level, on_ms LE16, off_ms LE16, count] */
#define HAPTIC_PATTERN_PAYLOAD_SIZE 6u
#define HAPTIC_PATTERN_TOTAL_SIZE (1u + HAPTIC_PATTERN_PAYLOAD_SIZE)
#define HAPTIC_LEVEL_OFFSET 1u
#define HAPTIC_ON_MS_LO_OFFSET 2u
#define HAPTIC_ON_MS_HI_OFFSET 3u
#define HAPTIC_OFF_MS_LO_OFFSET 4u
#define HAPTIC_OFF_MS_HI_OFFSET 5u
#define HAPTIC_COUNT_OFFSET 6u
#define HAPTIC_PATTERN_MAX_MS 5000u

#endif
